MvcKutuphane/Controllers/DuyuruController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
    public class DuyuruController : Controller
    {
        // GET: Duyuru
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLDUYURULAR.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniDuyuru()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniDuyuru(TBLDUYURULAR d)
        {
            db.TBLDUYURULAR.Add(d);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruSil(int id)
        {
            var duyuru = db.TBLDUYURULAR.Find(id);
            db.TBLDUYURULAR.Remove(duyuru);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruDetay(int id)
        {
            var duyuru = db.TBLDUYURULAR.Find(id);
            return View("DuyuruDetay", duyuru);
        }
        public ActionResult DuyuruGuncelle(TBLDUYURULAR dyr)
        {
            var duyuru = db.TBLDUYURULAR.Find(dyr.ID);
            duyuru.KATEGORI = dyr.KATEGORI;
            duyuru.ICERIK = dyr.ICERIK;
            duyuru.TARIH = dyr.TARIH;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Duyuru/DuyuruDetay.cshtml
@model MvcKutuphane.Models.Entity.TBLDUYURULAR
@{
    ViewBag.Title = "DuyuruDetay";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>DuyuruDetay</h2>

@using (Html.BeginForm("DuyuruGuncelle", "Duyuru", FormMethod.Post))
{
    <div style="margin-bottom: 15px"></div>
    <div class="form-group">
        <div style="margin-bottom:15px">
            <label>Duyuru ID</label>
            @Html.TextBoxFor(p => p.ID, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Duyuru Kategori</label>
            @Html.TextBoxFor(p => p.KATEGORI, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Duyuru İçerik</label>
            @Html.TextAreaFor(p => p.ICERIK, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Duyuru Tarih</label>
            @Html.TextBoxFor(p =>p.TARIH, "{0: dd.MM.yyyy}" ,new { @class = "form-control" })
        </div>
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}

MvcKutuphane/Views/Duyuru/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLDUYURULAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
    string renk = " ";
}

<h2>Duyurular</h2>

<table class="table table-bordered">
    <tr>
        <th>Duyuru No</th>
        <th>Kategori</th>
        <th>Tarih</th>
        <th>Sil</th>
        <th>İçerik</th>
    </tr>
    @foreach (var dyr in Model)
    {
        if(dyr.KATEGORI == "Diğer")
        {
            renk = "bg-info text-white";
        }
        if (dyr.KATEGORI == "Yeni Kitap")
        {
            renk = "bg-warning text-white";
        }
        if (dyr.KATEGORI == "İletişim")
        {
            renk = "bg-success text-white";
        }
        if (dyr.KATEGORI == "Kitapları Geciktirmeyin")
        {
            renk = "bg-danger text-white";
        }

        <tr class="@renk">
            <td>@dyr.ID</td>
            <td>@dyr.KATEGORI</td>
            <td>@Convert.ToDateTime(dyr.TARIH).ToString("dd/MM/yyyy")</td>
            <td><a href="/Duyuru/DuyuruSil/@dyr.ID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Duyuru/DuyuruDetay/@dyr.ID" class="btn btn-default" style="background-color:skyblue">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Duyuru/YeniDuyuru/" class="btn btn-primary">Yeni Duyuru Ekle</a>

MvcKutuphane/Views/Duyuru/YeniDuyuru.cshtml
@model MvcKutuphane.Models.Entity.TBLDUYURULAR
@{
    ViewBag.Title = "YeniDuyuru";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div style="margin-top:15px">
        <label>Duyuru Kategorisi</label>
        @Html.TextBoxFor(x => x.KATEGORI, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Duyuru İçerik</label>
        @Html.TextBoxFor(x => x.ICERIK, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Duyuru Tarihi</label>
        <input type="text" class="form-control" name="TARIH" value="@DateTime.Now.ToShortDateString()" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="Btn1">Duyuru Ekle</button>
    </div>
</form>