MvcKutuphane/Controllers/AyarlarController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
    public class AyarlarController : Controller
    {
        // GET: Ayarlar
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index()
        {
            var kullanicilar = db.TBLADMIN.ToList();
            return View(kullanicilar);
        }
        [HttpGet]
        public ActionResult YeniAdmin()
        {
            return View();
        }
        public ActionResult YeniAdmin(TBLADMIN p)
        {
            db.TBLADMIN.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult AdminSil(int id)
        {
            var adm = db.TBLADMIN.Find(id);
            db.TBLADMIN.Remove(adm);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult AdminGetir(int id) 
        {
            var admin = db.TBLADMIN.Find(id);
            return View("AdminGetir", admin); 
        }
        public ActionResult AdminGuncelle(TBLADMIN p)
        {
            var admin = db.TBLADMIN.Find(p.ID);
            admin.Kullanici = p.Kullanici;
            admin.Sifre = p.Sifre;
            admin.Yetki = p.Yetki;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Ayarlar/AdminGetir.cshtml
@model MvcKutuphane.Models.Entity.TBLADMIN
@{
    ViewBag.Title = "AdminGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("AdminGuncelle", "Ayarlar", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <label>ID</label>
        @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
        <br />
        <label>Kullanıcı</label>
        @Html.TextBoxFor(x => x.Kullanici, new { @class = "form-control" })
        <br />
        <label>Şifre</label>
        @Html.TextBoxFor(x => x.Sifre, new { @class = "form-control" })
        <br />
        <label>Yetki</label>
        @Html.TextBoxFor(x => x.Yetki, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}

MvcKutuphane/Views/Ayarlar/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLADMIN>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kullanıcı</th>
        <th>Yetki</th>
        <th>Sil</th>
        <th>Düzenle</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.Kullanici</td>
            <td>@x.Yetki</td>
            <td>
                <a class="btn btn-info btn-sm" href="/Ayarlar/AdminGetir/@x.ID">
                    <i class="fas fa-pencil-alt">
                    </i>
                    Düzenle
                </a>
            </td>
            <td>
                <a class="btn btn-danger btn-sm" href="/Ayarlar/AdminSil/@x.ID">
                    <i class="fas fa-trash">
                    </i>
                    Sil
                </a>
            </td>
        </tr>
    }
</table>
<br />
<button class="btn btn-primary" data-toggle="modal" data-target="#Modal1">Yeni Admin Ekle</button>
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background-color:lightslategray; color:aliceblue">
                <h3 class="modal-title">Admin Ekleme Paneli</h3>
            </div>
            <form method="post" action="/Ayarlar/YeniAdmin/">
                <div class="modal-body" style="background-color:whitesmoke">
                    <label>Kullanıcı Adı</label>
                    <input type="text" name="Kullanici" class="form-control" />
                    <br />
                    <label>Şifre</label>
                    <input type="text" name="Sifre" class="form-control" />
                    <br />
                    <label>Yetki</label>
                    <input type="text" name="Yetki" class="form-control" />
                    <br />
                    <button class="btn btn-sm btn-info">Kaydet</button>
                </div>
            </form>
        </div>
    </div>
</div>