MvcKutuphane/Controllers/KitapController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
    public class KitapController : Controller
    {
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index(string p)
        {
            var kitaplar = from k in db.TBLKITAP select k;
            if (!string.IsNullOrEmpty(p) && (!string.IsNullOrWhiteSpace(p))) // gelen p değerinin boş olması ve space değerlerinden oluşmaması durumlarında
            {
                kitaplar = kitaplar.Where(m => m.AD.Contains(p));
            }
            //var kitaplar = db.TBLKITAP.ToList();
            return View(kitaplar.ToList());
        }
        [HttpGet]
        public ActionResult KitapEkle()
        {  //Dropdown için Linq sorgusu ile liste oluşturma
            List<SelectListItem> deger1 = (from i in db.TBLKATEGORI.ToList()// Tblkategoriden i değeri gelecek ve 
                                           select new SelectListItem // yeni bir liste öğesi seçilecek.
                                           {
                                               Text = i.AD,
                                               Value = i.ID.ToString(),
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from i in db.TBLYAZAR.ToList()// Tblkategoriden i değeri gelecek ve 
                                           select new SelectListItem // yeni bir liste öğesi seçilecek.
                                           {
                                               Text = i.AD + ' ' + i.SOYAD,
                                               Value = i.ID.ToString(),
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            return View();
        }
        [HttpPost]
        public ActionResult KitapEkle(TBLKITAP p)
        {
            var ktg = db.TBLKATEGORI.Where(k => k.ID == p.TBLKATEGORI.ID).FirstOrDefault();
            var yzr = db.TBLYAZAR.Where(y => y.ID == p.TBLYAZAR.ID).FirstOrDefault();
            p.TBLKATEGORI = ktg;
            p.TBLYAZAR = yzr;
            db.TBLKITAP.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KitapSil(int id)
        {
            var kitap = db.TBLKITAP.Find(id);
            db.TBLKITAP.Remove(kitap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KitapGetir(int id)
        {
            var ktp = db.TBLKITAP.Find(id);
            List<SelectListItem> deger1 = (from i in db.TBLKATEGORI.ToList()// Tblkategoriden i değeri gelecek ve 
                                           select new SelectListItem // yeni bir liste öğesi seçilecek.
                                           {
                                               Text = i.AD,
                                               Value = i.ID.ToString(),
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from i in db.TBLYAZAR.ToList()// Tblkategoriden i değeri gelecek ve 
                                           select new SelectListItem // yeni bir liste öğesi seçilecek.
                                           {
                                               Text = i.AD + ' ' + i.SOYAD,
                                               Value = i.ID.ToString(),
                                           }).ToList();
            ViewBag.dgr2 = deger2;
            return View("KitapGetir", ktp);
        }
        public ActionResult KitapGuncelle(TBLKITAP p)
        {
            var kitap = db.TBLKITAP.Find(p.ID);
            kitap.AD = p.AD;
            kitap.BASIMYIL = p.BASIMYIL;
            kitap.SAYFA = p.SAYFA;
            kitap.YAYINEVI = p.YAYINEVI;
            kitap.DURUM = true;
            var ktg = db.TBLKATEGORI.Where(k => k.ID == p.TBLKATEGORI.ID).FirstOrDefault();
            var yzr = db.TBLYAZAR.Where(y => y.ID == p.TBLYAZAR.ID).FirstOrDefault();
            kitap.KATEGORI = ktg.ID;
            kitap.YAZAR = yzr.ID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Kitap/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLKITAP>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Kitap Sayfası</h2>

@using (Html.BeginForm("Index", "Kitap", FormMethod.Get)) 
{
<div style="margin-bottom:15px; margin-top:30px;">
    <b>Aranacak Kitap Adını Girin: &nbsp;</b>@Html.TextBox("p")
    <input type="submit" value="Ara" class="btn btn-xs btn-default" />
</div>
}

<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Kitap Adı</th>
        <th>Kategorisi</th>
        <th>Kitap Yazarı</th>
        <th>Basım Yılı</th>
        <th>Yayınevi</th>
        <th>Sayfa Sayısı</th>
        <th>Durum</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.ID</td>
            <td>@k.AD</td>
            <td>@k.KATEGORI</td>
            <td>@k.YAZAR</td>
            <td>@k.BASIMYIL</td>
            <td>@k.YAYINEVI</td>
            <td>@k.SAYFA</td>
            <td>@k.DURUM</td>
            <td><a href="/Kitap/KitapSil/@k.ID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Kitap/KitapGetir/@k.ID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>
<a href="/Kitap/KitapEkle/" class="btn btn-primary">Yeni Kitap Ekle</a>

MvcKutuphane/Views/Kitap/KitapEkle.cshtml
@model MvcKutuphane.Models.Entity.TBLKITAP
@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div style="margin-top:15px">
        <label>Kitap Adı</label>
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Kategori</label>
        @Html.DropDownListFor(k => k.TBLKATEGORI.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Yazar</label>
        @Html.DropDownListFor(k => k.TBLYAZAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Basım Yılı</label>
        @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Yayınevi</label>
        @Html.TextBoxFor(k => k.YAYINEVI, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Sayfa Sayısı</label>
        @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control" })
    </div>  
    <div style="margin-top:15px">
        <button class="btn btn-info">Kitap Ekle</button>
    </div>
    <input type="hidden" name="DURUM" value="true"/>
</form>

MvcKutuphane/Views/Kitap/KitapGetir.cshtml
@model MvcKutuphane.Models.Entity.TBLKITAP
@{
    ViewBag.Title = "KitapGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("KitapGuncelle", "Kitap", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <div style="margin-bottom:15px">
            <label>Kitap ID</label>
            @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Kitap Adı</label>
            @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Kategori</label>
            @Html.DropDownListFor(k => k.TBLKATEGORI.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Yazarı</label>
            @Html.DropDownListFor(k => k.TBLYAZAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Basım Yılı</label>
            @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Yayınevi</label>
            @Html.TextBoxFor(k => k.YAYINEVI, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Sayfa Sayısı</label>
            @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control" })
        </div>
    </div>
    <button class="btn btn-warning">Kitap Bilgilerini Güncelle</button>
    @*<input type="hidden" name="DURUM" value="true" />*@
}